version: "3.7"

services:
  # База данных
  postgres:
    container_name: sagelove_postgres
    image: postgres:10-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file: .env

  # Бэкенд Django WSGI
  backend:
    container_name: sagelove_backend
    build:
      context: ./backend
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/app
    command: /start.sh
    entrypoint: /entrypoint.sh
    restart: on-failure
    env_file: .env

  # Бэкенд Django ASGI
  backend_asgi:
    container_name: sagelove_backend_asgi
    build:
      context: ./backend
      dockerfile: Dockerfile.asgi
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/app
    command: /start_asgi.sh
    entrypoint: /entrypoint.sh
    restart: on-failure
    env_file: .env

  # Сборка фронтенда
  frontend:
    container_name: sagelove_frontend
    image: node:10-alpine
    command: npm run serve
    volumes:
      - ./.env:/app/.env:ro
      - ./frontend:/app
    working_dir: /app
    restart: on-failure

  # Веб-сервер
  nginx:
    container_name: sagelove_nginx
    image: nginx:alpine
    ports:
      - "8001:80"
    depends_on:
      - backend
    volumes:
      - ./backend/media/:/media/
      - ./backend/staticfiles/:/staticfiles/
      - ./nginx/dev.conf:/etc/nginx/nginx.conf:ro
    # logging:
    # driver: none

  # Брокер сообщений RabbitMQ
  redis:
    container_name: sagelove_redis
    restart: always
    image: redis:5-alpine
    env_file: .env

  celery-worker:
    container_name: sagelove_celery-worker
    restart: on-failure
    build:
      context: ./backend
    command: celery -A backend worker --loglevel=info --pool=solo
    volumes:
      - ./backend:/app
    env_file: .env
    depends_on:
      - backend
      - redis

  celery-beat:
    container_name: sagelove_celery-beat
    restart: on-failure
    build:
      context: ./backend
    command: celery -A backend beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - ./backend:/app
    env_file: .env
    depends_on:
      - backend
      - redis

  flower:
    container_name: sagelove_flower
    image: mher/flower
    depends_on:
      - redis
    env_file: .env
    ports:
      - 8888:8888

volumes:
  db_data: {}
